-- Append-only history for the authoritative platform certificate spot prices.
-- The calculator continues to read current prices exclusively from
-- public.platform_certificate_values.

create table if not exists public.platform_certificate_value_history (
  id bigint generated by default as identity primary key,
  effective_week date not null,
  observed_at timestamptz not null default now(),
  esc_spot_price numeric not null,
  prc_spot_price numeric not null,
  source text not null,
  observed_by_email text,
  constraint platform_certificate_value_history_esc_positive_check check (esc_spot_price > 0),
  constraint platform_certificate_value_history_prc_positive_check check (prc_spot_price > 0),
  constraint platform_certificate_value_history_source_present_check check (length(btrim(source)) > 0),
  constraint platform_certificate_value_history_week_value_unique unique (
    effective_week,
    esc_spot_price,
    prc_spot_price,
    source
  )
);

create index if not exists platform_certificate_value_history_observed_at_idx
on public.platform_certificate_value_history (observed_at desc);

alter table public.platform_certificate_value_history enable row level security;

drop policy if exists "admins can read platform certificate value history"
on public.platform_certificate_value_history;
create policy "admins can read platform certificate value history"
on public.platform_certificate_value_history
for select
to authenticated
using ((select public.is_approved_admin()));

drop policy if exists "admins can append platform certificate value history"
on public.platform_certificate_value_history;
create policy "admins can append platform certificate value history"
on public.platform_certificate_value_history
for insert
to authenticated
with check ((select public.is_approved_admin()));

revoke all on public.platform_certificate_value_history from anon, authenticated;
grant select, insert on public.platform_certificate_value_history to authenticated;
grant usage, select on sequence public.platform_certificate_value_history_id_seq to authenticated;

create or replace function public.capture_platform_certificate_value_history()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  insert into public.platform_certificate_value_history (
    effective_week,
    observed_at,
    esc_spot_price,
    prc_spot_price,
    source,
    observed_by_email
  )
  values (
    date_trunc('week', timezone('Australia/Sydney', coalesce(new.updated_at, now())))::date,
    coalesce(new.updated_at, now()),
    new.esc_spot_price,
    new.prc_spot_price,
    new.source,
    new.updated_by_email
  )
  on conflict (effective_week, esc_spot_price, prc_spot_price, source) do nothing;

  return new;
end;
$$;

drop trigger if exists capture_platform_certificate_value_history
on public.platform_certificate_values;
create trigger capture_platform_certificate_value_history
after insert or update of esc_spot_price, prc_spot_price, source, updated_at
on public.platform_certificate_values
for each row
execute function public.capture_platform_certificate_value_history();

insert into public.platform_certificate_value_history (
  effective_week,
  observed_at,
  esc_spot_price,
  prc_spot_price,
  source,
  observed_by_email
)
select
  date_trunc('week', timezone('Australia/Sydney', coalesce(updated_at, now())))::date,
  coalesce(updated_at, now()),
  esc_spot_price,
  prc_spot_price,
  source,
  updated_by_email
from public.platform_certificate_values
where id = 'global'
on conflict (effective_week, esc_spot_price, prc_spot_price, source) do nothing;
